### PR TITLE
Change project organization to io.zipkin.brave.play

### PR DESCRIPTION
**Pull request by shimamoto**
There are some remaining places that use the old organization. Those places are README and examples. We could completely remove the old organization in the next release.

### CODE REVIEW

**Comment by adriancole** [comment]
food for thought @llinder's work here is io.zipkin.brave.ratpack https://github.com/openzipkin-contrib/brave-ratpack/blob/master/pom.xml#L20

**Comment by takezoe** [comment]
Can we use `io.zipkin.brave.play` as the group id (organization in sbt) and the base package name? Also we need permission to publish artifacts to Sonatype.

**Comment by adriancole** [comment]
sounds good on maven group ID. you might want to consider "brave.play"
on package name so that in case this is moved to ASF we don't have to
rename the packages (group id is a smaller matter).

on sonatype can you request to be added here? It has been my
experience that they always just add people who ask :)
https://issues.sonatype.org/browse/OSSRH-16669

**Comment by shimamoto** [comment]
Fixed. Thanks for the jira link! I'll request access before releasing the next version.

**Comment by takezoe** [comment]
@adriancole Do you mean we can use package names other than `org.apache.*` even after we move to ASF?

**Comment by adriancole** [comment]
> @adriancole <https://github.com/adriancole> Do you mean we can use
> package names other than org.apache.* even after we move to ASF?
>
yes

**Comment by takezoe** [comment]
@adriancole I got it, thanks!

**Comment by adriancole** [comment]
thanks very much

**Pull request merged**
